name: fog-ros-baseimage

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/*'
  workflow_dispatch:

jobs:
  build:
    name: fog-ros-baseimage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container metadata
        id: meta # referenced from later step
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/tiiuae/fog-ros-baseimage
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=sha

      - name: Container metadata for builder
        id: meta_builder # referenced from later step
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/tiiuae/fog-ros-baseimage-builder
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=sha

      - name: Container metadata for coverity
        id: meta_coverity # referenced from later step
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/tiiuae/fog-ros-baseimage-builder-coverity
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push base image
        uses: docker/build-push-action@v4
        if: github.event_name == 'push'
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push builder
        uses: docker/build-push-action@v4
        if: github.event_name == 'push'
        with:
          push: true
          context: .
          file: Dockerfile.builder
          tags: ${{ steps.meta_builder.outputs.tags }}
          labels: ${{ steps.meta_builder.outputs.labels }}

      - name: Build and push coverity # Needs to be last because it depends on the builder image built above
        uses: docker/build-push-action@v4
        if: github.event_name == 'push'
        with:
          push: true
          context: .
          file: Dockerfile.coverity
          tags: ${{ steps.meta_coverity.outputs.tags }}
          labels: ${{ steps.meta_coverity.outputs.labels }}
          build-args: |
            "COVERITY_DOCKER_REGISTRY_USERNAME=${{ secrets.COVERITY_DOCKER_REGISTRY_USERNAME }}"
            "COVERITY_DOCKER_REGISTRY_ACCESS_TOKEN=${{ secrets.COVERITY_DOCKER_REGISTRY_ACCESS_TOKEN }}"
            "COVERITY_LICENSE_DAT_B64=${{ secrets.COVERITY_LICENSE_DAT_B64 }}"
            "COVERITY_ACCESS_TOKEN_B64=${{ secrets.COVERITY_ACCESS_TOKEN_B64 }}"
